In [17]:
# 필요한 라이브러리 불러오기
import torch
import numpy as np

# 텐서 초기화  
- 데이터로부터 직접 생성하기
- Numpy 배열로부터 생성하기
- 다른 텐서로부터 생성하기

In [18]:
data = [[1,2],[3,4]]

x_data = torch.tensor(data)
print(x_data)

np_array = np.array(data)
x_np = torch.from_numpy(np_array)
print(x_np)

x_ones = torch.ones_like(x_data) # x_data의 속성을 유지함
print(f"Ones Tensor : \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float) # x_data의 속성을 덮어씀
print(f"Random Tensor : \n {x_rand} \n")

tensor([[1, 2],
        [3, 4]])
tensor([[1, 2],
        [3, 4]])
Ones Tensor : 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor : 
 tensor([[0.6694, 0.9888],
        [0.0119, 0.1295]]) 



무작위(random) 또는 상수(constant) 값을 사용하기
- shape은 텐서의 dimension(차원)을 나타내는 tuple(튜플)로, 아래 함수들에서는 출력 텐서의 차원을 결정한다.

In [19]:
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor : \n {rand_tensor} \n")
print(f"Ones Tensor : \n {ones_tensor} \n")
print(f"Zeros Tensor : \n {zeros_tensor} \n")

Random Tensor : 
 tensor([[0.2335, 0.3885, 0.5053],
        [0.7663, 0.0094, 0.8673]]) 

Ones Tensor : 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor : 
 tensor([[0., 0., 0.],
        [0., 0., 0.]]) 



텐서의 attribute(속성)은 텐서의 shape(모양), datatype(자료형) 및 어느 장치(device)에 저장되는지를 나타낸다.

In [20]:
tensor = torch.rand(3,4)

print(f"Shape of Tensor : {tensor.shape}")
print(f"Datatype of Tensor : {tensor.dtype}")
print(f"Device tensor is sotred on : {tensor.device}")

Shape of Tensor : torch.Size([3, 4])
Datatype of Tensor : torch.float32
Device tensor is sotred on : cpu


# Tensor Operation(텐서 연산)  
- transposing(전치), indexing, slicing, 수학적 연산, 선형대수, random sampling 등 여러 연산을 수행할 수 있다.
- 각 연산들은 GPU에서 실행 가능하다.
- 기본적으로 tensor는 CPU에 생성된다. '.to' method를 사용하면 환경이 따라준다는 전제조건 하에 GPU로 연산을 돌릴 수 있다.

In [21]:
# GPU가 존재하면 텐서를 이동한다
if torch.cuda.is_available() :
    tensor = tensor.to("cuda")

NumPy식의 표준 인덱싱과 슬라이싱

In [22]:
tensor = torch.ones(4,4)
print(f"First row : {tensor[0]}")
print(f"First column : {tensor[:,0]}")
print(f"Last column : {tensor[...,-1]}")
tensor[:,1] = 0
print(tensor)

First row : tensor([1., 1., 1., 1.])
First column : tensor([1., 1., 1., 1.])
Last column : tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


텐서 합치기
- torch.cat을 사용해서 주어진 차원에 따라 일련의 텐서를 연결할 수 있다. torch.cat과 미묘하게 다른 텐서 결합 연산으로 torch.stack도 있다.

In [23]:
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


산술 연산(arithmetic operations)

In [24]:
# 두 tensor 간의 행렬 곱(matrix multiplication)을 계산하자. y1, y2, y3은 모두 같은 값을 갖는다.
y1 = tensor @ tensor.T
print(y1)
y2 = tensor.matmul(tensor.T)
print(y2)
y3 = torch.rand_like(y1)
print(y3)
torch.matmul(tensor, tensor.T, out=y3)

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])
tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])
tensor([[0.5150, 0.3842, 0.1937, 0.2993],
        [0.9147, 0.4309, 0.6926, 0.1981],
        [0.1518, 0.8733, 0.5491, 0.5732],
        [0.8508, 0.2443, 0.9682, 0.6091]])


tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])

In [25]:
# 요소별 곱(elment-wise product)을 계산하자. z1, z2, z3은 모두 같은 값을 갖는다.
z1 = tensor * tensor
print(z1)
z2 = tensor.mul(tensor)
print(z2)
z3 = torch.rand_like(tensor)
print(z3)
torch.mul(tensor, tensor, out=z3)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
tensor([[0.3416, 0.7651, 0.6930, 0.4195],
        [0.3064, 0.9493, 0.9594, 0.9198],
        [0.1931, 0.1745, 0.3845, 0.9680],
        [0.8217, 0.6850, 0.5053, 0.9116]])


tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

단일 요소 텐서(single element tensor)
- 텐서의 모든 값을 하나로 집계(aggregate)하여 요소가 하나인 텐서의 경우, item()을 사용하여 Python 숫자 값으로 변환할 수 있다.

In [26]:
agg = tensor.sum()
agg_item = agg.item()
print(agg_item, type(agg_item))

12.0 <class 'float'>


바꿔치기 연산(in-place)
- 연산 결과를 피연산자(operand)에 저장하는 연산을 바꿔치기 연산이라고 부르며, _ 접미사를 갖는다. 
- 예를 들어 x.copy_(y)나 x.t_()는 x를 변경한다.
- 이 연산은 메모리를 일부 절약할 수 있지만, history(기록)이 즉시 삭제되어 derivative(도함수) 계산에 문제가 발생할 수 있어 권장하지 않는다.

In [27]:
print(f"{tensor} \n")
tensor.add_(5)
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


NumPy 변환(Bridge)
- CPU 상의 텐서와 NumPy 배열은 메모리 공간을 공유하므로, 하나를 변경하면 다른 하나도 변경된다.

In [28]:
# 텐서를 numpy 배열로 변환하기
t = torch.ones(5)
print(f"t : {t}")
n = t.numpy()
print(f"n : {n}")

t : tensor([1., 1., 1., 1., 1.])
n : [1. 1. 1. 1. 1.]


- 텐서의 변경사항이 numpy 배열에 반영된다.

In [29]:
t.add_(1)
print(f"t : {t}")
print(f"n : {n}")

t : tensor([2., 2., 2., 2., 2.])
n : [2. 2. 2. 2. 2.]


numpy 배열을 텐서로 변환하기

In [30]:
n = np.ones(5)
t = torch.from_numpy(n)

- numpy 배열의 변경 사항이 텐서에 반영된다.

In [31]:
np.add(n, 1, out=n)
print(f"t : {t}")
print(f"n : {n}")

t : tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n : [2. 2. 2. 2. 2.]
