# PyTorch Tutorial로 독학하기
- URL from : https://tutorials.pytorch.kr/beginner/blitz/tensor_tutorial.html
- URL from : https://pytorch.org/tutorials/beginner/blitz/tensor_tutorial.html
- URL from : https://pytorch.org/docs/stable/generated/torch.stack.html

# Tensor
tensor는 array(배열)나 matrix(행렬)과 매우 유사한 특수한 자료구조다. PyTorch에서는 tensor를 사용하여 모델의 입출력뿐만 아닌, 모델의 매개변수를 encode(부호화)한다.  
GPU나 다른 연산 가속을 위한 특수한 하드웨어에서 실행할 수 있다는 점을 제외하면, tensor는 NumPy의 ndarray와 매우 유사하다.

In [1]:
import torch
import numpy as np

## tensor 초기화하기
tensor는 여러가지 방법으로 초기화할 수 있다. 아래에서 하나씩 해보자.

### 데이터로부터 직접(directly) 생성하기
데이터로부터 직접 tensor를 생성할 수 있다. 데이터의 자료형(data type)은 자동으로 유추해서 만들어준다.

In [2]:
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)

### NumPy 배열로부터 생성하기
tensor는 NumPy 배열로 생성할 수 있다. 그 반대도 가능하다.

In [3]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

### 다른 tensor로부터 생성하기
명시적으로 재정의(override)하지 않는다면, 인자로 주어진 tensor의 속성(모양(shape), 자료형(datatype))을 유지한다.

In [4]:
x_ones = torch.ones_like(x_data) # x_data의 속성을 유지한다
print(f"Ones Tensor : \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float) # x_data의 속성을 덮어쓴다
print(f"Random Tensor : \n {x_rand} \n")

Ones Tensor : 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor : 
 tensor([[0.2866, 0.9574],
        [0.9851, 0.1472]]) 



### 무작위(random) 또는 상수(constant) 값을 사용하기  
```shape```은  tensor의 차원(dimension)을 나타내는 tuple로, 아래 함수들에서는 출력 tensor의 차원을 결정한다.

In [5]:
shape = (2, 3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor : \n {rand_tensor} \n")
print(f"Ones Tensor : \n {ones_tensor} \n")
print(f"Zeros Tensor : \n {zeros_tensor} \n")

Random Tensor : 
 tensor([[0.2371, 0.0587, 0.6256],
        [0.3414, 0.3823, 0.3501]]) 

Ones Tensor : 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor : 
 tensor([[0., 0., 0.],
        [0., 0., 0.]]) 



## tensor의 속성(attribute)
tensor의 속성은 텐서의 모양(shape), 자료형( datatype), 및 어느 장치에 저장되는지를 나타낸다.

In [6]:
tensor = torch.rand(3, 4)
print(f"Shape of tensor  : {tensor.shape}")
print(f"Datatype of tensor  : {tensor.dtype}")
print(f"Device tensor is stored on tensor  : {tensor.device}")

Shape of tensor  : torch.Size([3, 4])
Datatype of tensor  : torch.float32
Device tensor is stored on tensor  : cpu


## tensor 연산(operation)
전치(transposing), 인덱싱(indexing), 슬라이싱(slicing), 수학 계산, 선형 대수, 임의 샘플링(random sampling) 등, 100가지 이상의 tensor 연산이 가능하다.  
각 연산들은 일반적으로 CPU보다  빠른 GPU에서 실행할 수 있다.

In [7]:
# GPU가 존재한다면 tensor를 이동시켜보자
if torch.cuda.is_available() :
    tensor = tensor.to('cuda')
    print(f"Device tensor is stored on : {tensor.device}")

Device tensor is stored on : cuda:0


### NumPy식의 표준 인덱싱과 슬라이싱

In [8]:
tensor = torch.ones(4, 4)
tensor[:, 1] = 0
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


### Tensor 합치기
```torch.cat```을 사용하여 주어진 차원에 따라 일련의 tensor를 연결할 수 있다. ```torch.cat```과 미묘하게 다른 또 다른 tensor 결합 연산으로는 ```torch.stack```이 있다.

In [9]:
# torch.cat 사용하기
t1 =  torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


In [10]:
"""# torch.stack 사용하기
torch.stack(tensors, dim=0, *, out=None) # --> Tensor"""
# https://pytorch.org/docs/stable/generated/torch.stack.html

'# torch.stack 사용하기\ntorch.stack(tensors, dim=0, *, out=None) # --> Tensor'

### tensor 곱하기

In [11]:
# 요소별 곱(element-wise product) 계산하기
print(f"tensor.mul(tensor) \n {tensor.mul(tensor)} \n")
# 다른 문법으로는 :
print(f"tensor * tensor \n {tensor * tensor}")

tensor.mul(tensor) 
 tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor * tensor 
 tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


두 tensor 간의 행렬 곱(matrix multiplication)을 계산해보자

In [12]:
print(f"tensor.matmul(tensor.T) \n {tensor.matmul(tensor.T)} \n")
# 다른 문법으로는 :
print(f"tensor @ tensor.T \n {tensor @ tensor.T}")

tensor.matmul(tensor.T) 
 tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]]) 

tensor @ tensor.T 
 tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])


### 바꿔치기(in-place) 연산
```_``` 접미사를 갖는 연산들은 바꿔치기(in-place) 연산이다. 예를 들어, ```x.copy_()```나 ```x.t_()```는 x를 변경하는 연산이다.
- 바꿔치기 연산은 메모리를 일부 절약하지만, 기록(history)이 즉시 삭제되어 도함수(derivative) 계산에 문제가 발생할 수 있다. 해서, 사용을 권장하지는 않는다고 한다.

In [13]:
print(tensor, "\n")
tensor.add_(5)
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


## NumPy 변환(Bridge)
CPU 상의 tensor와 NumPy 배열은 메모리 공간을 공유하기 때문에, 하나를 변경하면 다른 하나도 변경된다.

### tensor를 NumPy 배열로 변환하기

In [14]:
t = torch.ones(5)
print(f"t : {t}")
n = t.numpy()
print(f"n : {n}")

t : tensor([1., 1., 1., 1., 1.])
n : [1. 1. 1. 1. 1.]


tensor의 변경 사항이 NumPy 배열에 반영된다.

In [15]:
t.add_(1)
print(f"t : {t}")
print(f"n : {n}")

t : tensor([2., 2., 2., 2., 2.])
n : [2. 2. 2. 2. 2.]


### NumPy 배열을 tensor로 변환하기

In [16]:
n = np.ones(5)
t = torch.from_numpy(n)

NumPy 배열의 변경 사항이 tensor에 반영된다.

In [17]:
np.add(n, 1, out=n)
print(f"t : {t}")
print(f"n : {n}")

t : tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n : [2. 2. 2. 2. 2.]
